Repository riecenaidoo/discord-music-bot, pull requests merged in 2023-11, with the labels that each got.

#83 Api intergration
  requirements.txt
  src/api.py
  src/main.py
  tests/client.py
Labels: refine

#88 Dev Build Script
  Makefile
  README.MD
  requirements-dev.txt
Labels: documentation, quality of life

#90 Prealpha Build
  requirements.txt
  src/console.py
  src/main.py
Labels: bug
